name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          workflow_conclusion: success
          name: release_assets
          path: /tmp/release/
          if_no_artifact_found: fail

      - name: Extract version from manifest.json
        id: extract_version
        run: |
          VERSION=$(cat /tmp/release/manifest.json | grep 'version' | awk '{print $2}' | sed 's/[",]//g')
          echo "Extracted Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create Git Tag
        if: steps.extract_version.outputs.version
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        if: steps.extract_version.outputs.version
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/release/*
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_title: Release ${{ steps.extract_version.outputs.version }}
          generate_release_notes: true
